name = "tht-autoinsertion-site"
pages_build_output_dir = "."
compatibility_date = "2025-12-02"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "tht_database"
database_id = "28bed2b5-b7b7-4511-82c4-1694f883ce2a"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "tht-product-images"

[[kv_namespaces]]
binding = "STATIC_ASSETS"
id = "3483bad1eb214b5094c45f0b69c50ff0"
