import { createLayout, pageHero, icon } from './layout';

export async function contactPage() {
  const content = `${pageHero('RFQ & line assessment','Give engineering the facts behind your target.','A useful first proposal starts with the PCB, component mix, output target and current process.','<a class="btn btn-primary" href="https://api.whatsapp.com/send?phone=8613602562576&text=Hi%20Jason%2C%20I%20would%20like%20a%20THT%20line%20assessment." target="_blank" rel="noopener">WhatsApp Jason</a>')}
  <section class="section"><div class="shell grid grid-2"><aside><span class="eyebrow">Direct contact</span><h2 style="font-size:40px">Talk to a sales engineer.</h2><div class="metric"><strong>Jason Wu</strong><span>Global sales contact</span></div><div class="metric"><strong>+86 136 0256 2576</strong><span>Phone / WhatsApp / WeChat</span></div><div class="metric"><strong>jasonwu@smthelp.com</strong><span>Corporate email</span></div><div class="notice" style="margin-top:22px">Bao'an District, Shenzhen, China. Factory visit details are confirmed with your appointment.</div></aside>
  <form class="form-card" id="rfq-form"><div class="form-grid"><div class="field"><label for="name">Full name *</label><input class="input" id="name" autocomplete="name" required></div><div class="field"><label for="email">Corporate email *</label><input class="input" id="email" type="email" autocomplete="email" required></div><div class="field"><label for="company">Company *</label><input class="input" id="company" autocomplete="organization" required></div><div class="field"><label for="application">PCB application *</label><select class="input" id="application" required><option value="">Select</option><option>Power supply</option><option>LED / lighting</option><option>Appliance</option><option>Automotive electronics</option><option>Industrial control</option><option>Other</option></select></div><div class="field"><label for="volume">Monthly target (boards) *</label><input class="input" id="volume" type="number" min="1" required></div><div class="field"><label for="process">Current process *</label><select class="input" id="process" required><option>Manual insertion</option><option>Semi-automatic</option><option>Existing auto insertion</option><option>New factory</option></select></div><div class="field full"><label for="timeline">Deployment timeline *</label><select class="input" id="timeline" required><option>Within 3 months</option><option>3-6 months</option><option>Planning phase</option></select></div><div class="field full"><label for="message">Components, models or constraints</label><textarea class="input" id="message"></textarea></div><div class="field full"><button class="btn btn-primary" type="submit">Submit line assessment ${icon('arrow',16)}</button><p class="status" id="rfq-status" aria-live="polite"></p></div></div></form></div></section>`;
  const scripts = `<script>document.getElementById('rfq-form').addEventListener('submit',async e=>{e.preventDefault();const value=id=>document.getElementById(id).value;const s=document.getElementById('rfq-status'),btn=e.submitter;btn.disabled=true;s.textContent='Submitting your assessment...';const data={name:value('name'),email:value('email'),company:value('company'),message:'Application: '+value('application')+' | Monthly target: '+value('volume')+' | Current process: '+value('process')+' | Timeline: '+value('timeline')+' | Notes: '+value('message')};try{const r=await fetch('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error();e.target.reset();s.textContent='Received. A sales engineer will review your application.'}catch(err){s.textContent='Could not submit. Please email jasonwu@smthelp.com.'}finally{btn.disabled=false}})</script>`;
  return new Response(createLayout('Request a THT Line Assessment',content,scripts,'Send Southern Machinery your PCB application, production volume and automation target for a THT line assessment.'),{headers:{'Content-Type':'text/html;charset=UTF-8'}});
}
