import { createLayout, icon } from './layout';
import { images, machines, machineCards } from './marketing-data';

export async function homePage() {
  const content = `<section class="page-hero"><div class="shell"><span class="eyebrow">Turnkey THT automation · Shenzhen engineering</span><h1>Remove manual bottlenecks from your THT line.</h1><p>Southern Machinery designs insertion, board handling and wave soldering systems around your components, PCB flow and output target.</p><div class="hero-actions"><a class="btn btn-primary" href="/contact">Get a turnkey plan ${icon('arrow',16)}</a><a class="btn btn-secondary" style="color:#fff;border-color:#4b616d" href="/solutions">Map your line</a></div></div></section><div class="shell stats"><div class="metric"><strong>Since 2011</strong><span>Shenzhen-based manufacturing</span></div><div class="metric"><strong>237+</strong><span>Global EMS partners reported</span></div><div class="metric"><strong>SMT + THT</strong><span>One engineering conversation</span></div><div class="metric"><strong>Line-ready</strong><span>Machine, handling and process</span></div></div>
  <section class="section"><div class="shell"><div class="section-head"><div><span class="eyebrow">Core systems</span><h2>Start with the component. Build the line around it.</h2></div><p>Choose the insertion family by lead form and feeding method. Final configuration is confirmed against component samples and PCB data.</p></div><div class="grid grid-3">${machineCards([machines[0],machines[3],machines[4]])}</div></div></section>
  <section class="section section-dark"><div class="shell"><div class="section-head"><div><span class="eyebrow">Why Southern Machinery</span><h2>Engineering depth without a fragmented supplier chain.</h2></div></div><div class="grid grid-4"><article><div class="feature-icon">${icon('check')}</div><h3>Direct engineering</h3><p>Application review and customization from Shenzhen manufacturing teams.</p></article><article><div class="feature-icon">${icon('check')}</div><h3>ROI-fit configuration</h3><p>Capacity and labor assumptions are made visible before equipment selection.</p></article><article><div class="feature-icon">${icon('check')}</div><h3>Service planning</h3><p>Installation, training, remote diagnostics and critical spare-parts planning.</p></article><article><div class="feature-icon">${icon('check')}</div><h3>Complete integration</h3><p>Insertion, handling, inspection and soldering designed as one process flow.</p></article></div></div></section>
  <section class="section section-alt"><div class="shell grid grid-2" style="align-items:center"><div><span class="eyebrow">Line engineering</span><h2 style="font-size:42px;line-height:1.12">See the entire THT process before you buy a machine.</h2><p style="color:var(--ink-2)">Share a component list, PCB files, current staffing and target output. Our team will identify the insertion families, transfer points and soldering process that need engineering confirmation.</p><div class="hero-actions"><a class="btn btn-primary" href="/contact">Book a line assessment</a><a class="btn btn-secondary" href="/ad-studio">Create sales visuals</a></div></div><img src="${images.line}" alt="Southern Machinery complete THT auto insertion production line" loading="lazy" width="900" height="600" style="width:100%;aspect-ratio:3/2;object-fit:cover"></div></section>`;
  return new Response(createLayout('THT Auto Insertion Machines & Turnkey Lines', content, '', 'Southern Machinery builds THT auto insertion machines, board handling and wave soldering lines for global EMS factories.'), {headers:{'Content-Type':'text/html;charset=UTF-8'}});
}
